version: 2
updates:
  - package-ecosystem: gomod
    directory: "/"
    schedule:
      interval: weekly
    open-pull-requests-limit: 5
    commit-message:
      prefix: "chore(deps)"
    groups:
      k8s:
        patterns:
          - "k8s.io/*"
      charm:
        patterns:
          - "github.com/charmbracelet/*"

  - package-ecosystem: github-actions
    directory: "/"
    schedule:
      interval: weekly
    open-pull-requests-limit: 3
    commit-message:
      prefix: "chore(ci)"
